version: '3.8'

services:
  # Servicio de Eureka
  eureka-shop-service:
    build: eureka-shop-service
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'super-shop-network'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Servicio de productos
  products-shop-service:
    build: products-shop-service
    mem_limit: 512m
    ports:
      - "9000:9000"
    environment:
      DB_URL: "${DB_URL_PRODUCT}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-shop-service:8761/eureka/
    networks:
      - 'super-shop-network'
    depends_on:
      eureka-shop-service:
        condition: service_healthy
      postgres-database-product:
        condition: service_healthy

  # Servicio de carrito
  car-shop-service:
    build: car-shop-service
    mem_limit: 512m
    ports:
      - "9005:9005"
   
    environment:
      DB_URL: "${DB_URL_CAR}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-shop-service:8761/eureka/
    networks:
      - 'super-shop-network'
    depends_on:
      eureka-shop-service:
        condition: service_healthy
      postgres-database-car:
        condition: service_healthy

  # Servicio de ventas
  sale-shop-service:
    build: sale-shop-service
    mem_limit: 512m
    ports:
      - "9010:9010"
    environment:
      DB_URL: "${DB_URL_SALE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-shop-service:8761/eureka/

    networks:
      - 'super-shop-network'
    depends_on:
      eureka-shop-service:
        condition: service_healthy
      postgres-database-sale:
        condition: service_healthy

  # Base de datos Postgres para ventas
  postgres-database-sale:
    image: postgres:17
    container_name: postgres-database-sale
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: shop_sale_service
    restart: always
    networks:
      - 'super-shop-network'
    healthcheck:
      test: ["CMD", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Base de datos Postgres para carrito
  postgres-database-car:
    image: postgres:17
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: shop_car_service
    restart: always
    networks:
      - 'super-shop-network'
    healthcheck:
      test: ["CMD", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Base de datos Postgres para productos
  postgres-database-product:
    image: postgres:17
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: shop_product_service
    restart: always
    networks:
      - 'super-shop-network'
    healthcheck:
      test: ["CMD", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  super-shop-network: